version: '3.2'

services:
  # Php-fpm container
  shelter_backend:
    build: images/backend
    image: shelter_backend
    volumes:
      - type: bind
        source: ./src
        target: /var/www/shelter
    networks:
      shelter:
        ipv4_address: 192.160.1.1

  # Nginx container
  shelter_nginx:
    build: images/nginx
    image: shelter_nginx
    ports:
      - '8080:80'
    volumes:
      - type: bind
        source: ./src
        target: /var/www/shelter
      - type: bind
        source: ./storage/files
        target: /var/www/files
    networks:
      shelter:
        ipv4_address: 192.160.1.2

  # Database container
  shelter_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shelter
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    networks:
      shelter:
        ipv4_address: 192.160.1.3

networks:
  shelter:
    driver: bridge
    ipam:
      config:
        - subnet: 192.160.1.0/16