version: '3.2'

services:
  # Php-fpm container
  shelter_backend:
    build: images/backend
    image: shelter_backend
    volumes:
      - type: bind
        source: ./src
        target: /var/www/shelter

  # Nginx container
  shelter_nginx:
    build: images/nginx
    image: shelter_nginx
    ports:
      - '8080:80'
    volumes:
      - type: bind
        source: ./src
        target: /var/www/shelter
      - type: bind
        source: ./storage/files
        target: /var/www/files

  # Database container
  shelter_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shelter
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    ports: 
      - '3307:3306'
