version: '3.2'

services:
  frontend:
    build: ./frontend
    image: shelter_frontend
    depends_on:
      - backend
    ports:
      - '8080:80'
    volumes:
      - ./frontend/public:/var/www/shelter/public
      - ./backend/src/public/res:/var/www/shelter/public/res
    networks:
      shelter:
        ipv4_address: 192.168.1.2

  backend:
    build: ./backend
    image: shelter_backend
    depends_on:
      - db
    volumes:
      - ./backend/src:/var/www/shelter
    networks:
      shelter:
        ipv4_address: 192.168.1.3

  db:
    image: mysql
    restart: always
    environment:
      command: --default-authentication-plugin=mysql_native_password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shelter
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    volumes:
    - ./storage/mysql:/var/lib/mysql:rw
    networks:
      shelter:
        ipv4_address: 192.168.1.4

networks:
  shelter:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/29